# Numpy Module:
- Numpy library is used for working with arrays
- Numpy stands for numerical Python
- Computation operations

In [2]:
import numpy as np
l = [1,2,3,4,5,6]
arr = np.array(l)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
l1 = list(range(1,11))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Dimensions in Arrays:


In [5]:
# 1 - D Array
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [6]:
# 2-D Array
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# 3 - D Array
arr2 = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr2)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


In [12]:
from numpy import random
print(random.rand(2))
print(random.randint(4))

[0.07125424 0.95505214]
3


In [18]:
# Create n dimensional array with random integer value
print(random.randint(100,size = 3))
print(random.randint(100,size = (3,4)))
print(random.randint(100,size = (4,3)))
print(random.randint(100,size = (3,4,2)))

[63 54 24]
[[81 77 97 24]
 [57 61 69 47]
 [77 16 23 76]]
[[69 17 12]
 [74 58 65]
 [68 54 94]
 [74 68 68]]
[[[14  4]
  [49 11]
  [46 50]
  [37 30]]

 [[84 38]
  [48 38]
  [43 73]
  [48 44]]

 [[96  9]
  [46  3]
  [70 92]
  [30 29]]]


In [22]:
# create n dimension array with random floating point value
from numpy import random
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))
print(random.rand(3,4,2))

0.5413721339079817
[0.27198842 0.74203406 0.96481171]
[[0.09594317 0.30923058 0.73194294]
 [0.49087959 0.05758204 0.81879205]]
[[[0.27435186 0.38637512]
  [0.56092671 0.07860688]
  [0.71105488 0.73413921]
  [0.07570772 0.89493439]]

 [[0.33013283 0.24412355]
  [0.05856053 0.39546911]
  [0.75977998 0.85625955]
  [0.46758644 0.40689522]]

 [[0.79237005 0.70704385]
  [0.46573683 0.60101239]
  [0.6677463  0.59427815]
  [0.22787407 0.41288743]]]
